config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: 'landing#index'
  get :about, to: 'about#aboutpage'
  get :items, to: 'items#index'
  get :faq, to: 'faq#index'

  get :'cart/show', to: "cart#show"
  post :add_item, to: "cart#add_item"
  delete :remove_item, to: "cart#remove_item"
  patch :update_item, to: "cart#update_item"

  resources :orders, only: [:new, :create, :show]
  post :braintree, to: "orders#braintree"
  # get :braintree, to: "orders#new"
  post :billplz, to: "orders#billplz"
  scope '/webhooks', controller: :webhooks do
    post 'payment_callback', to: 'webhooks#payment_callback', as: :payment_callback
  end

  devise_for :users, controllers:
    {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  devise_scope :user do
    get :"/auth/facebook/callback", to: redirect { |path_params, req| '/users/auth/facebook/callback' }
    post :"/auth/facebook/callback", to: redirect { |path_params, req| '/users/auth/facebook/callback' }
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  respond_to :js
  # before_action :authenticate_user!
  before_action :load_cart
  # after_action :write_cart, only: [:remove_item, :update_item]

  include CartHelper

  def add_item
    if @cart[params[:id]]
      quantity = params[:quantity].to_i
      quantityOld = @cart[params[:id]].to_i
      @cart[params[:id]] = quantityOld + quantity
    else
      @cart[params[:id]] = params[:quantity]
    end
    flash.now[:success] = "You've added item to cart."
    cookies[:cart] = JSON.generate(@cart)
  end

  def update_item
    if @cart[params[:id]]
      @cart[params[:id]] = params[:quantity]
    end
    cookies[:cart] = JSON.generate(@cart)
    @update_item = getCartItemFromId params[:id], params[:quantity]
    flash.now[:success] = "You've updated your cart."
  end

  def remove_item
    @cart.delete params[:id]
    flash.now[:danger] = "Item removed!"
    cookies[:cart] = JSON.generate(@cart)
    @deletable_item = params[:id]
  end

  def load_cart
    if cookies[:cart]
      @cart = JSON.parse(cookies[:cart])
    else
      @cart = {}
    end
  end

  # def write_cart
  #   cookies[:cart] = JSON.generate(@cart)
  # end


end

app/helpers/cart_helper.rb
module CartHelper

  def carts_hash
    return {} unless cookies[:cart]

    cart =  JSON.parse(cookies[:cart])
    total_price = 0
    items = []

    cart.each do |item_id, quantity|
      item = getCartItemFromId item_id, quantity
      if !item
        next
      end
      total_price += item.total
      items << item
    end
    { total_price: total_price, items: items }
  end

  def getCartItemFromId(id, quantity)
    item = Item.find_by(id: id)

    if !item
      return
    end

    item.define_singleton_method(:quantity) { quantity }
    item.define_singleton_method(:total) { item.price * quantity.to_f }

    return item
  end
end

app/views/cart/_NO_modalbody.html.erb
<div class="modal-body">
  <h5 class="text-center">Feel free to add more stuffs in your cart!</h5>
  <div class="table table-striped" id="tblGrid">
    <div id="tblHead">
      <div class='row'>
      <b>
        <div class="col-xs-3">Items</div>
        <div class="col-xs-3">Price</div>
        <div class="col-xs-3">Quantity</div>
        <div class="col-xs-3 text-right">Subtotal</div>
      </b>
      </div>
    </div>
  <tbody>
    <% if cart[:items] && cart[:items].length > 0 %>
      <% cart[:items].each do |item| %>
      <%= render partial: "cart/item", locals: {item: item} %>
      <%end%>
    <%end%>
  </tbody>
  </div>

  <div class=row>
    <div class='col-md-12'>
      <h3 style='text-align: right; font-weight: bold;'>
        Total Price

        <br>
        <div id="total-cart-price"> 
          <%= number_to_currency(cart[:total_price], :unit => 'RM') %>
        </div>
      </h3>
    </div>
  </div>
</div>

app/views/cart/_item.html.erb
<div class="row cart-item" data-id="<%= item.id %>">
  <div class="col-xs-3"><a tabindex="0" data-toggle="popover" data-trigger="focus" title="<%= item.description %>" data-content="<%= item.description %>"><%= item.title %></a></div>
  <div class="col-xs-3"><%= number_to_currency(item.price, :unit => 'RM') %></div>
    <div class="col-xs-3"><%= form_tag update_item_path(id: item), remote: true, method: :patch do %>
      <%= text_field_tag :quantity, item.quantity, size: 5 %>
      <%= submit_tag 'Update', class: "btn btn-primary" %>
    <%end%>
    </div>
    <div class="col-xs-3 text-right"><%= number_to_currency(item.total, unit: 'RM') %>
      <%= link_to "", remove_item_path(id: item), class: "fa fa-times btn btn-danger", remote: true, method: :delete %>
    </div>

</div>

app/views/cart/_show.html.erb
<div class="modal fade-modal-lg" id="cartmodal-modal-lg">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 class="modal-title">Your Cart</h3>
      </div>

      <div class="modal-body">
        <h5 class="text-center">Hit the <b>SHOP</b> button to add more items to your cart!</h5>
        <br>
        <div class="table table-striped" id="tblGrid">
          <div id="tblHead">
            <div class='row'>
            <b>
              <div class="col-xs-3">Items</div>
              <div class="col-xs-3">Price</div>
              <div class="col-xs-3">Quantity</div>
              <div class="col-xs-3 text-right">Subtotal</div>
            </b>
            </div>
          </div>
          <tbody>
            <% if @cart && cart[:items].length > 0 %>
              <% cart[:items].each do |item| %>
                <%= render partial: "cart/item", locals: {item: item} %>
              <%end%>
            <%end%>
          </tbody>
        </div>

        <div class=row>
          <div class='col-md-12'>
            <h3 style='text-align: right; font-weight: bold;'>
              Total Price
              <br>
              <div id="total-cart-price"> 
                <%= number_to_currency(cart[:total_price], :unit => 'RM') %>
              </div>
            </h3>
          </div>
        </div>

      </div>

      <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button> -->
          <!-- <button type="button" class="btn btn-danger pull-left">More Items</button> -->
          <%= link_to "Shop", items_path, method: :get, class: "btn btn-danger pull-left" %>
          <%= link_to "BILLPLZ", billplz_path, method: :post, class: "btn btn-primary" %>
          <%= link_to "VISA/Master", new_order_path, class: "btn btn-success" %>

      </div>

    </div>
  </div>
</div>

app/views/cart/_xxshow.html.erb
<div class="modal fade" id="cartmodal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      <div class= "finalcart text-center">
        <h1> Your Cart</h1>
      </div>

        <% if cart.empty? %>
          Your Cart Is Currently Empty
        <% else %>
          <div class="cart-content" data-id="<%= cart[:items][0].id %>">
            <table>
              <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Selected items</th>
              <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Quantity</th>
              <!-- <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Price</th> -->
              <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Subtotal</th>
              <% cart[:items].each do |item| %>
              <tr>
                <td>
                <a tabindex="0" data-toggle="popover" data-trigger="focus" title="<%= item.description %>" data-content="<%= item.description %>"><%= item.title %></a>


                </td>
                <td>
                    <%= form_tag update_item_path(id: item), remote: true, method: :patch do %>
                    <%= text_field_tag :quantity, item.quantity %>
                    <%= submit_tag 'Update', class: "btn btn-primary" %>
                    <%= link_to "", remove_item_path(id: item), class: "fa fa-times btn btn-danger", remote: true, method: :delete %>
                    <%end%>
                </td>
                <!-- <td>
                  <%= number_to_currency(item.price, :unit => 'RM') %>
                </td> -->
                <td>
                  <%= number_to_currency(item.total, unit: 'RM') %>
                </td>
              </tr>
              <% end %>

            </table>
          </div>

          <div class=row>
            <div class='col-md-12'>
              <h3 style='text-align: right; font-weight: bold;'>
                Total Price
                <br><%= number_to_currency(cart[:total_price], :unit => 'RM') %>
              </h3>
            </div>
          </div>
          <%= link_to "BILLPLZ", billplz_path, method: :post, class: "btn btn-primary" %>
          <%= link_to "VISA/Mastercard", new_order_path, class: "btn btn-success" %>
        <% end %>

                <!-- content section -->
        <section class="content-section">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 shop-cart-table">
                        <table class="table shop-cart text-center">
                            <thead>
                                <tr>
                                    <th class="first"></th>
                                    <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Product</th>
                                    <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Price</th>
                                    <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Quantity</th>
                                    <th class="text-left text-uppercase font-weight-600 letter-spacing-2 text-small black-text">Sub Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="product-thumbnail text-left">
                                        <a href="shop-single-product.html"><img src="http://placehold.it/120x120" alt="" ></a>
                                    </td>
                                    <td class="text-left">
                                        <a href="shop-single-product.html">Chasse Wells Italian Genuine Leather Incroyable Tote</a>
                                        <span class="text-uppercase display-block text-small margin-two">SKU: 290397</span>
                                        <a href="shop-single-product.html" class="text-small"><i class="fa fa-edit black-text"></i> Edit</a>
                                    </td>
                                    <td class="text-left">
                                        $450
                                    </td>
                                    <td class="product-quantity">
                                        <div class="select-style med-input shop-shorting shop-shorting-cart no-border-round">
                                            <select>
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                                <option value="6">6</option>
                                            </select>
                                        </div>
                                    </td>
                                    <td class="product-subtotal text-left">$450</td>
                                    <td class="product-remove text-center">
                                        <a href="javascript:void(0)"><i class="fa fa-times"></i></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/cart/add_item.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")
$("#cart-container").html("<%=j render partial: 'cart/show', locals: { cart: carts_hash } %>")

app/views/cart/remove_item.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")
$('.cart-item[data-id=<%=@deletable_item%>]').remove()
$('#total-cart-price').html("<%= number_to_currency(carts_hash[:total_price], :unit => 'RM') %>")

app/views/cart/update_item.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")
$('.cart-item[data-id=<%= @update_item.id %>]').replaceWith("<%=j render partial: 'cart/item', locals: { item: @update_item } %>")
$('#total-cart-price').html("<%=j number_to_currency(carts_hash[:total_price], :unit => 'RM') %>")