config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: 'landing#index'
  get :about, to: 'about#aboutpage'
  get :items, to: 'items#index'
  get :faq, to: 'faq#index'

  get :'cart/show', to: "cart#show"
  post :add_item, to: "cart#add_item"
  delete :remove_item, to: "cart#remove_item"
  patch :update_item, to: "cart#update_item"

  resources :orders, only: [:new, :create, :show]
  post :braintree, to: "orders#braintree"
  # get :braintree, to: "orders#new"
  post :billplz, to: "orders#billplz"
  scope '/webhooks', controller: :webhooks do
    post 'payment_callback', to: 'webhooks#payment_callback', as: :payment_callback
  end

  devise_for :users, controllers:
    {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  devise_scope :user do
    get :"/auth/facebook/callback", to: redirect { |path_params, req| '/users/auth/facebook/callback' }
    post :"/auth/facebook/callback", to: redirect { |path_params, req| '/users/auth/facebook/callback' }
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_paper_trail
  belongs_to :category
  has_many :ordered_items
  has_many :orders, through: :ordered_items
  mount_uploader :image, ImageUploader
  searchkick word_start: [:title , :description]

  after_save :reindex_item


  def reindex_item
    reindex
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @categories = Category.all

    @items = Item.all

    if params[:query].present?
      @items = Item.search(
      params[:query],
      fields: [:title , :description],
      match: :word_start,
      operator: "or")
    else
      @items = Item.all
    end
  end
end

app/views/items/index.html.erb
<div class="panel-group" id="accordion">

    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag "category1.jpg", class:"img-circle img-responsive" %>
        <h4 class="panel-title">
          <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">Home Accessories</a>
        </h4>
      </div>
      <div id="collapseFour" class="panel-collapse collapse">
        <div class="panel-body text-center">
          <% @items.each do |item| %>
            <% if item.category_id == 1 %>
            <%image = item.image.url || "" %>
            <%= image_tag image, class:"img-responsive", width:"350px", height:"350px" %>
            <h4><%= item.title %></h4>
            <%= item.description %>
            <h5>RM<%= item.price %></h5>
            <%= link_to "Add To Cart", add_item_path(id: item, quantity: 1), method: :post, remote: true %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag "category2.jpg", class:"img-circle img-responsive" %>
        <h4 class="panel-title">
          <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">Arts & Craft</a>
        </h4>
      </div>
      <div id="collapseSeven" class="panel-collapse collapse">
        <div class="panel-body text-center">
          <% @items.each do |item| %>
            <% if item.category_id == 2 %>
            <%image = item.image.url || "" %>
            <%= image_tag image, class:"img-responsive", width:"200px", height:"200px" %>
            <h3><%= item.title %></h3>
            <h5><%= item.description %></h5>
            <h5>RM<%= item.price %></h5>
            <%= link_to "Add To Cart", add_item_path(id: item, quantity: 1), method: :post, remote: true %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>